spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8


#配置mybatis
mybatis:
  mapper-locations: classpath:com/dongruan/dao/*.xml